<?php
declare(strict_types=1);

/**
 * Config-driven, role/permission-aware menu.
 * Keys: label, route?, icon, roles[], perms[], active[], children[].
 */

require_once __DIR__ . '/../shared/training_features.php';
require_once __DIR__ . '/../shared/testing_features.php';

$testingEnabled = screen_testing_features_enabled($GLOBALS['conn'] ?? null);
$trainingEnabled = training_features_enabled($GLOBALS['conn'] ?? null);

return [

  [
    'label' => 'Intelligence',
    'code'  => 'IE',
    'icon'  => 'cpu',
    'roles' => [],
    'perms' => ['INTEL_VIEW','INTEL_ADMIN','INTEL_FORECAST_VIEW','INTEL_FORECAST_CREATE','INTEL_SCENARIO_CREATE','ML_VIEW','ML_ADMIN','AI_VIEW','AI_ADMIN','AI_VIEW_AUDIT','ADMIN_ALL','SYSADMIN'],
    'active' => ['intelligence/*','ai-dataset/*'],
    'children' => [
      ['label'=>'Intelligence Dashboard','code'=>'IEDB','route'=>'intelligence/index','icon'=>'speedometer2','active'=>['intelligence/index'],'roles'=>[],'perms'=>['INTEL_VIEW','INTEL_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Engine Health','code'=>'IEHE','route'=>'intelligence/health','icon'=>'heart-pulse','active'=>['intelligence/health'],'roles'=>[],'perms'=>['INTEL_VIEW','INTEL_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Dataset Analysis','code'=>'IEDA','route'=>'ai-dataset/index','icon'=>'graph-up-arrow','active'=>['ai-dataset/index'],'roles'=>[],'perms'=>['ANALYSIS_DATASET_ANALYZE','ANALYSIS_DATASET_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Analysis Datasets','code'=>'IEDS','route'=>'ai-dataset/datasets','icon'=>'database','active'=>['ai-dataset/datasets','ai-dataset/dataset-form'],'roles'=>[],'perms'=>['ANALYSIS_DATASET_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Budget Ledger Version Roles','code'=>'IEVR','route'=>'intelligence/budget-ledger-version-roles','icon'=>'diagram-2','active'=>['intelligence/budget-ledger-version-roles'],'roles'=>[],'perms'=>['INTEL_ADMIN','ML_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'ML Model Register','code'=>'IEML','route'=>'intelligence/ml-models','icon'=>'diagram-3','active'=>['intelligence/ml-models'],'roles'=>[],'perms'=>['ML_VIEW','ML_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'AI / Engine Config','code'=>'IECF','route'=>'intelligence/config','icon'=>'sliders','active'=>['intelligence/config'],'roles'=>[],'perms'=>['INTEL_ADMIN','AI_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Engine Runs Audit','code'=>'IERU','route'=>'intelligence/runs','icon'=>'clock-history','active'=>['intelligence/runs'],'roles'=>[],'perms'=>['AI_VIEW_AUDIT','INTEL_ADMIN','ADMIN_ALL','SYSADMIN']],
    ],
  ],

  [
    'label'  => __t('menu_home'),
    'route'  => 'home/index',
    'icon'   => 'house',
    'active' => ['home/*'],
    'roles'  => [],
    'perms'  => ['AUTHENTICATED'],
  ],

  [
    'label' => 'Help & Knowledge',
    'code'  => 'HK',
    'icon'  => 'stars',
    'roles' => [],
    'perms' => ['AI_HELP_USE','AI_HELP_ADMIN','AI_HELP_UPLOAD','AI_HELP_VIEW_LOGS','ANALYSIS_DATASET_ANALYZE','ANALYSIS_DATASET_ADMIN','ANALYSIS_DATASET_VIEW_LOGS','ADMIN_ALL','SYSADMIN'],
    'active' => ['ai-knowledge/*','ai-dataset/*'],
    'children' => [
      ['label'=>'Ask CBMS Assistant','code'=>'HKAI','route'=>'ai-knowledge/ask','icon'=>'stars','active'=>['ai-knowledge/ask'],'roles'=>[],'perms'=>['AI_HELP_USE','AI_HELP_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'AI Knowledge Base','code'=>'HKKB','route'=>'ai-knowledge/admin','icon'=>'database','active'=>['ai-knowledge/admin'],'roles'=>[],'perms'=>['AI_HELP_ADMIN','AI_HELP_UPLOAD','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Knowledge Documents','code'=>'HKDO','route'=>'ai-knowledge/documents','icon'=>'files','active'=>['ai-knowledge/documents','ai-knowledge/chunks'],'roles'=>[],'perms'=>['AI_HELP_ADMIN','AI_HELP_UPLOAD','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Upload Knowledge','code'=>'HKUP','route'=>'ai-knowledge/upload','icon'=>'upload','active'=>['ai-knowledge/upload'],'roles'=>[],'perms'=>['AI_HELP_UPLOAD','AI_HELP_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'AI Question Logs','code'=>'HKLG','route'=>'ai-knowledge/logs','icon'=>'clock-history','active'=>['ai-knowledge/logs'],'roles'=>[],'perms'=>['AI_HELP_VIEW_LOGS','AI_HELP_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'AI Usage Dashboard','code'=>'HKUS','route'=>'ai-knowledge/usage','icon'=>'bar-chart-line','active'=>['ai-knowledge/usage'],'roles'=>[],'perms'=>['AI_HELP_VIEW_LOGS','AI_HELP_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Dataset Analysis','code'=>'HKDA','route'=>'ai-dataset/index','icon'=>'graph-up-arrow','active'=>['ai-dataset/index'],'roles'=>[],'perms'=>['ANALYSIS_DATASET_ANALYZE','ANALYSIS_DATASET_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Analysis Datasets','code'=>'HKDS','route'=>'ai-dataset/datasets','icon'=>'database','active'=>['ai-dataset/datasets','ai-dataset/dataset-form'],'roles'=>[],'perms'=>['ANALYSIS_DATASET_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Analysis Dataset Logs','code'=>'HKDL','route'=>'ai-dataset/logs','icon'=>'shield-lock','active'=>['ai-dataset/logs'],'roles'=>[],'perms'=>['ANALYSIS_DATASET_VIEW_LOGS','ANALYSIS_DATASET_ADMIN','ADMIN_ALL','SYSADMIN']],
    ],
  ],

  [
    'label' => 'Budget Strategy',
    'code'  => 'SF',
    'icon'  => 'flag',
    'roles' => [],
    'perms' => ['STRATEGY_VIEW','STRATEGY_REPORT_VIEW','STRATEGY_CONFIG_EDIT','STRATEGY_SETUP_EDIT','STRATEGY_PERFORMANCE_EDIT','STRATEGY_DELIVERY_EDIT','STRATEGY_GOVERNANCE_EDIT','STRATEGY_FISCAL_EDIT','STRATEGY_WORKFLOW_EDIT','STRATEGY_SUBMISSION_PREPARE','STRATEGY_SUBMISSION_REVIEW','STRATEGY_SUBMISSION_APPROVE','STRATEGY_PUBLISH','ADMIN_ALL','SYSADMIN'],
    'active' => ['strategy/*','strategy-setup/*','strategy-performance/*','strategy-delivery/*','strategy-governance/*','strategy-submissions/*','strategy-fiscal/*'],
    'children' => [
      [
        'label' => 'Start',
        'code'  => 'SFSR',
        'icon'  => 'compass',
        'roles' => [],
        'perms' => ['STRATEGY_VIEW','STRATEGY_REPORT_VIEW','STRATEGY_WORKFLOW_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>__t('menu_strategy_overview'),'code'=>'SFOH','route'=>'strategy/index','icon'=>'flag','roles'=>[],'perms'=>['STRATEGY_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Framework Guide','code'=>'SFGD','route'=>'strategy/framework-guide','icon'=>'map','roles'=>[],'perms'=>['STRATEGY_VIEW','STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Planning Framework',
        'code'  => 'SFPF',
        'icon'  => 'bullseye',
        'roles' => [],
        'perms' => ['STRATEGY_PERFORMANCE_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Strategic Pillars','code'=>'SFPI','route'=>'strategy-performance/strategic-pillars','icon'=>'stack','roles'=>[],'perms'=>['STRATEGY_PERFORMANCE_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Goals','code'=>'SFGO','route'=>'strategy-performance/goals','icon'=>'signpost-split','roles'=>[],'perms'=>['STRATEGY_PERFORMANCE_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Objectives','code'=>'SFOB','route'=>'strategy-performance/objectives','icon'=>'bullseye','roles'=>[],'perms'=>['STRATEGY_PERFORMANCE_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Indicators','code'=>'SFIN','route'=>'strategy-performance/indicators','icon'=>'speedometer2','roles'=>[],'perms'=>['STRATEGY_PERFORMANCE_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Indicator Targets','code'=>'SFTA','route'=>'strategy-performance/targets','icon'=>'graph-up-arrow','roles'=>[],'perms'=>['STRATEGY_PERFORMANCE_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Program Structure',
        'code'  => 'SFST',
        'icon'  => 'diagram-3',
        'roles' => [],
        'perms' => ['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Sectors','code'=>'SFSE','route'=>'strategy-setup/sectors','icon'=>'grid','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Programs','code'=>'SFPG','route'=>'strategy-setup/programs','icon'=>'kanban','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'SubPrograms','code'=>'SFSP','route'=>'strategy-setup/sub-programs','icon'=>'diagram-2','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Projects','code'=>'SFPJ','route'=>'strategy-setup/projects','icon'=>'kanban-fill','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Funding Types','code'=>'SFFT','route'=>'strategy-setup/funding-types','icon'=>'collection','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Funding Sources','code'=>'SFFS','route'=>'strategy-setup/funding-sources','icon'=>'bank','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Economic Items','code'=>'SFEI','route'=>'strategy-setup/economic-items','icon'=>'tags','roles'=>[],'perms'=>['STRATEGY_SETUP_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Fiscal Framework',
        'code'  => 'SFFF',
        'icon'  => 'bank',
        'roles' => [],
        'perms' => ['STRATEGY_FISCAL_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>__t('menu_fiscal_overview'),'code'=>'SFFO','route'=>'strategy-fiscal/overview','icon'=>'bank','roles'=>[],'perms'=>['STRATEGY_FISCAL_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Resource Envelope Summary','code'=>'SFRE','route'=>'strategy-fiscal/resource-envelope','icon'=>'calendar3','roles'=>[],'perms'=>['STRATEGY_FISCAL_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_fiscal_envelope'),'code'=>'SFRL','route'=>'strategy-fiscal/resource-envelope-lines','icon'=>'list-ul','roles'=>[],'perms'=>['STRATEGY_FISCAL_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_fiscal_ceilings'),'code'=>'SFSC','route'=>'strategy-fiscal/sector-ceilings','icon'=>'grid-3x3-gap','roles'=>[],'perms'=>['STRATEGY_FISCAL_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Ceiling vs Strategic Plan','code'=>'SFCP','route'=>'strategy-fiscal/ceiling-vs-plan','icon'=>'arrows-collapse','roles'=>[],'perms'=>['STRATEGY_FISCAL_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Delivery & Costing',
        'code'  => 'SFDC',
        'icon'  => 'box-seam',
        'roles' => [],
        'perms' => ['STRATEGY_DELIVERY_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Outputs','code'=>'SFOT','route'=>'strategy-delivery/outputs','icon'=>'box-seam','roles'=>[],'perms'=>['STRATEGY_DELIVERY_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Activities','code'=>'SFAC','route'=>'strategy-delivery/activities','icon'=>'list-task','roles'=>[],'perms'=>['STRATEGY_DELIVERY_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Activity Budgets','code'=>'SFAB','route'=>'strategy-delivery/budgets','icon'=>'cash-stack','roles'=>[],'perms'=>['STRATEGY_DELIVERY_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Governance',
        'code'  => 'SFGV',
        'icon'  => 'shield-check',
        'roles' => [],
        'perms' => ['STRATEGY_GOVERNANCE_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'BSP Narratives','code'=>'SFNA','route'=>'strategy-governance/narratives','icon'=>'journal-richtext','roles'=>[],'perms'=>['STRATEGY_GOVERNANCE_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Fiscal Risks','code'=>'SFFR','route'=>'strategy-governance/fiscal-risks','icon'=>'shield-exclamation','roles'=>[],'perms'=>['STRATEGY_GOVERNANCE_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Program Risks','code'=>'SFGR','route'=>'strategy-governance/program-risks','icon'=>'link-45deg','roles'=>[],'perms'=>['STRATEGY_GOVERNANCE_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Funding Requests',
        'code'  => 'SFFW',
        'icon'  => 'cash-coin',
        'roles' => [],
        'perms' => ['STRATEGY_SUBMISSION_PREPARE','STRATEGY_SUBMISSION_REVIEW','STRATEGY_SUBMISSION_APPROVE','STRATEGY_PUBLISH','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Funding Lodgements','code'=>'BSLG','route'=>'strategy-submissions/lodgements','icon'=>'cash-coin','roles'=>[],'perms'=>['STRATEGY_SUBMISSION_PREPARE','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Funding Reviews','code'=>'BSRV','route'=>'strategy-submissions/reviews','icon'=>'clipboard-check','roles'=>[],'perms'=>['STRATEGY_SUBMISSION_REVIEW','STRATEGY_SUBMISSION_APPROVE','STRATEGY_PUBLISH','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Funding Approvals','code'=>'BSAP','route'=>'strategy-submissions/approvals','icon'=>'stamp','roles'=>[],'perms'=>['STRATEGY_SUBMISSION_APPROVE','STRATEGY_PUBLISH','ADMIN_ALL','SYSADMIN']],
          ['label'=>'All Funding Items','code'=>'BSFI','route'=>'strategy-submissions/list','icon'=>'list-ul','roles'=>[],'perms'=>['STRATEGY_SUBMISSION_PREPARE','STRATEGY_SUBMISSION_REVIEW','STRATEGY_SUBMISSION_APPROVE','STRATEGY_PUBLISH','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Funding Submission Summary','code'=>'BSFS','route'=>'strategy-submissions/report','icon'=>'bar-chart','roles'=>[],'perms'=>['STRATEGY_SUBMISSION_PREPARE','STRATEGY_SUBMISSION_REVIEW','STRATEGY_SUBMISSION_APPROVE','STRATEGY_PUBLISH','ADMIN_ALL','SYSADMIN']],
        ],
      ],
    ],
  ],

  [
    'label' => 'Budget Planning',
    'code'  => 'BS',
    'icon'  => 'journal-text',
    'roles' => [],
    'perms' => ['ESTIMATES_VIEW','ESTIMATES_EDIT','RATES_VIEW','RATES_EDIT','RATES_CREATE','ADMIN_ALL','SYSADMIN'],
    'active' => ['transaction-input/*','rates/*','ceilings/*','budgets/*'],
    'children' => [
      [
        'label' => 'Budget Input',
        'code'  => 'BSBI',
        'icon'  => 'journal-text',
        'roles' => [],
        'perms' => ['ESTIMATES_VIEW','ESTIMATES_EDIT','RATES_VIEW','RATES_EDIT','RATES_CREATE','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>__t('menu_transaction_input_list'),'code'=>'BSTL','route'=>'transaction-input/list','icon'=>'journal-text','active'=>['transaction-input/list'],'roles'=>[],'perms'=>['ESTIMATES_VIEW','ESTIMATES_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_transaction_input_editor'),'code'=>'BSTE','route'=>'transaction-input/editor','icon'=>'pencil-square','active'=>['transaction-input/editor'],'roles'=>[],'perms'=>['ESTIMATES_VIEW','ESTIMATES_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Ceiling Management',
        'code'  => 'BSCM',
        'icon'  => 'safe2',
        'roles' => [],
        'perms' => ['ESTIMATES_VIEW','ESTIMATES_EDIT','FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Ceiling Balances','code'=>'BSCB','route'=>'ceilings/balances','icon'=>'safe2','active'=>['ceilings/*'],'roles'=>[],'perms'=>['ESTIMATES_VIEW','ESTIMATES_EDIT','FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Ceiling Balance Keys','code'=>'BSCK','route'=>'ceilings/balances-keys','icon'=>'key','active'=>['ceilings/*'],'roles'=>[],'perms'=>['ESTIMATES_VIEW','ESTIMATES_EDIT','FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Processing Tools',
        'code'  => 'BSPR',
        'icon'  => 'cpu',
        'roles' => [],
        'perms' => ['ESTIMATES_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Transaction Stub Runner','code'=>'BSST','route'=>'transaction-input/stub','icon'=>'play-circle','active'=>['transaction-input/stub'],'roles'=>[],'perms'=>['ESTIMATES_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Batch Runner','code'=>'BSBR','route'=>'transaction-input/batch-runner','icon'=>'collection-play','active'=>['transaction-input/batch-runner'],'roles'=>[],'perms'=>['ESTIMATES_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Single Save Load Test','code'=>'BSSL','route'=>'transaction-input/single-save-load-test','icon'=>'speedometer2','active'=>['transaction-input/single-save-load-test'],'roles'=>[],'perms'=>['ESTIMATES_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN']],
        ],
      ],
    ],
  ],

  [
    'label' => 'Budget Execution',
    'code'  => 'BE',
    'icon'  => 'play-circle',
    'roles' => [],
    'perms' => ['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL'],
    'children' => [
      ['label'=>'Setup & Rollover','code'=>'BESR','route'=>'execution/index','icon'=>'gear-wide-connected','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>'Opening Balances','code'=>'BEOB','route'=>'execution/opening-balances','icon'=>'table','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>__t('menu_execution_warrants'),'code'=>'BEWR','route'=>'execution/warrants','icon'=>'check2-square','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>'Supplementary Budgets','code'=>'BESB','route'=>'execution/supplementaries','icon'=>'plus-square','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>'Budget Reductions','code'=>'BEBR','route'=>'execution/budget-reductions','icon'=>'dash-square','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>'Reservations','code'=>'BERS','route'=>'execution/reservations','icon'=>'bookmark-check','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>'RIE','code'=>'BERI','route'=>'execution/rie','icon'=>'file-earmark-check','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>'Commitments','code'=>'BECM','route'=>'execution/commitments','icon'=>'journal-check','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>__t('menu_execution_realloc'),'code'=>'BERE','route'=>'execution/index','icon'=>'check2-square','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
      ['label'=>__t('menu_execution_virements'),'code'=>'BEVI','route'=>'execution/index','icon'=>'check2-square','active'=>['execution/*'],'roles'=>[],'perms'=>['BUDGET_EXECUTION_VIEW','BUDGET_EXECUTION_EDIT','BUDGET_EXECUTION_REVIEW','BUDGET_EXECUTION_ADMIN','ADMIN_ALL']],
    ],
  ],

  [
    'label' => 'Organisation & Chart of Accounts',
    'code'  => 'OC',
    'icon'  => 'diagram-3',
    'roles' => [],
    'perms' => ['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','DATAOBJECTCODES_VIEW','DATAOBJECTCODES_EDIT','DATAOBJECTCODES_IMPORT','DATAOBJECTCODES_ACCESS_ADMIN','DATAOBJECTCODES_ADMIN','STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN'],
    'active' => ['dataobject-types/*','dataobjectcodes/*','dataobjectworkflow/*','segments/*','segment-values/*','strategy-reports/segment-parent-child'],
    'children' => [
      [
        'label' => 'Data Objects',
        'code'  => 'OCDA',
        'icon'  => 'collection',
        'roles' => [],
        'perms' => ['DATAOBJECTCODES_VIEW','DATAOBJECTCODES_EDIT','DATAOBJECTCODES_IMPORT','DATAOBJECTCODES_ADMIN','ADMIN_ALL'],
        'children' => [
          ['label'=>'Data Object Types','code'=>'ADOT','route'=>'dataobject-types/list','icon'=>'diagram-3','active'=>['dataobject-types/*'],'roles'=>[],'perms'=>['DATAOBJECTCODES_VIEW','DATAOBJECTCODES_EDIT','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
          ['label'=>'Data Object Codes','code'=>'ADOC','route'=>'dataobjectcodes/index','icon'=>'collection','active'=>['dataobjectcodes/*'],'roles'=>[],'perms'=>['DATAOBJECTCODES_VIEW','DATAOBJECTCODES_EDIT','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
          ['label'=>'Data Object Hierarchy','code'=>'ADOH','route'=>'dataobjectcodes/hierarchy','icon'=>'diagram-2','active'=>['dataobjectcodes/hierarchy'],'roles'=>[],'perms'=>['DATAOBJECTCODES_VIEW','DATAOBJECTCODES_EDIT','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
          ['label'=>'Load Data Object Codes from Segment Values','code'=>'ADOS','route'=>'dataobjectcodes/syncOrgFromSegments','icon'=>'arrow-repeat','active'=>['dataobjectcodes/syncOrgFromSegments'],'roles'=>[],'perms'=>['DATAOBJECTCODES_IMPORT','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
          ['label'=>'Add Data Object Code','code'=>'ADDC','route'=>'dataobjectcodes/create','icon'=>'plus-circle','active'=>['dataobjectcodes/create'],'roles'=>[],'perms'=>['DATAOBJECTCODES_EDIT','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
        ],
      ],
      [
        'label' => 'Segments',
        'code'  => 'OCSG',
        'icon'  => 'sliders2-vertical',
        'roles' => [],
        'perms' => ['SEGMENTS_VIEW','SEGMENTS_EDIT','SEGMENT_VALUES_IMPORT','BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Segments','code'=>'BASE','route'=>'segments/list','icon'=>'sliders2-vertical','active'=>['segments/*'],'roles'=>[],'perms'=>['SEGMENTS_VIEW','SEGMENTS_EDIT','BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL']],
          ['label'=>'Segment Values','code'=>'BASV','route'=>'segment-values/list','icon'=>'diagram-3','active'=>['segment-values/*'],'roles'=>[],'perms'=>['SEGMENTS_VIEW','SEGMENTS_EDIT','BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL']],
          ['label'=>'Segment Parent-Child Check','code'=>'RSPC','route'=>'strategy-reports/segment-parent-child','icon'=>'diagram-2','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Data Object Access',
        'code'  => 'OCAC',
        'icon'  => 'shield-lock',
        'roles' => [],
        'perms' => ['DATAOBJECTCODES_ACCESS_ADMIN','DATAOBJECTCODES_ADMIN','ADMIN_ALL'],
        'children' => [
          ['label'=>'Access Management','code'=>'ADAM','route'=>'dataobjectcodes/access','icon'=>'shield-lock','active'=>['dataobjectcodes/access*'],'roles'=>[],'perms'=>['DATAOBJECTCODES_ACCESS_ADMIN','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
          ['label'=>'Grant Access','code'=>'ADGA','route'=>'dataobjectcodes/access_form','icon'=>'person-plus','active'=>['dataobjectcodes/access_form'],'roles'=>[],'perms'=>['DATAOBJECTCODES_ACCESS_ADMIN','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
          ['label'=>'Workflow Status','code'=>'ADOW','route'=>'dataobjectworkflow/statuses','icon'=>'list-check','active'=>['dataobjectworkflow/*'],'roles'=>[],'perms'=>['DATAOBJECTCODES_VIEW','DATAOBJECTCODES_EDIT','DATAOBJECTCODES_ADMIN','ADMIN_ALL']],
        ],
      ],
    ],
  ],

  [
    'label' => 'Reports & Analysis',
    'code'  => 'RA',
    'icon'  => 'file-earmark-text',
    'roles' => [],
    'perms' => ['STRATEGY_REPORT_VIEW','ANALYTICS_VIEW','DASHBOARD_VIEW','DASHBOARD_ADMIN','ADMIN_ALL','SYSADMIN'],
    'active' => ['reports/*','analytics*','scenario-results*','dashboard/*'],
    'children' => [
      [
        'label' => 'Formal Reports',
        'code'  => 'RPFR',
        'icon'  => 'printer',
        'roles' => [],
        'perms' => ['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Approved Budget Report','code'=>'RPAB','route'=>'reports/execute','href'=>'index.php?route=reports/execute&code=RPT_APPROVED_BUDGET','icon'=>'play-circle','active'=>['reports/execute','reports/run'],'roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Report Catalogue','code'=>'RPCA','route'=>'reports/catalogue','icon'=>'file-earmark-text','active'=>['reports/catalogue','reports/run'],'roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Report Run History','code'=>'RPRH','route'=>'reports/history','icon'=>'clock-history','active'=>['reports/history','reports/run-detail'],'roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Strategy Reports',
        'code'  => 'RPBR',
        'icon'  => 'bar-chart-line',
        'roles' => [],
        'perms' => ['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Strategic Summary','code'=>'RPSU','route'=>'strategy-reports/summary','icon'=>'clipboard-data','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Sector Budget Report','code'=>'RPSB','route'=>'strategy-reports/sector-budget','icon'=>'grid-3x3-gap','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Program Budget Report','code'=>'RPPB','route'=>'strategy-reports/program-budget','icon'=>'kanban','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Project Budget Report','code'=>'RPJB','route'=>'strategy-reports/project-budget','icon'=>'kanban-fill','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'MTFF View','code'=>'RPMT','route'=>'strategy-reports/mtff','icon'=>'bar-chart-line','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Performance Report','code'=>'RPPF','route'=>'strategy-reports/performance','icon'=>'graph-up-arrow','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Dashboards',
        'code'  => 'DB',
        'icon'  => 'pie-chart',
        'roles' => [],
        'perms' => ['DASHBOARD_VIEW','DASHBOARD_ADMIN','ANALYTICS_VIEW','ADMIN_ALL'],
        'children' => [
          ['label'=>'Dashboard','code'=>'DBOV','route'=>'dashboard/index','icon'=>'graph-up','active'=>['dashboard/*'],'roles'=>[],'perms'=>['DASHBOARD_VIEW','DASHBOARD_ADMIN','ADMIN_ALL']],
          ['label'=>'Flexmonster Dashboard','code'=>'DBFX','route'=>'dashboard/flexdash','icon'=>'bar-chart-line-fill','active'=>['dashboard/flexdash'],'roles'=>[],'perms'=>['DASHBOARD_VIEW','DASHBOARD_ADMIN','ANALYTICS_VIEW','ADMIN_ALL']],
        ],
      ],
      [
        'label' => __t('menu_analytics'),
        'code'  => 'AN',
        'icon'  => 'bar-chart',
        'roles' => [],
        'perms' => ['ANALYTICS_VIEW'],
        'children' => [
          ['label'=>'Overview','code'=>'ANOV','route'=>'analytics','icon'=>'speedometer','roles'=>[],'perms'=>['ANALYTICS_VIEW']],
          ['label'=>'Scenario Results','code'=>'ANSR','route'=>'scenario-results/index','icon'=>'table','roles'=>[],'perms'=>['ANALYTICS_VIEW']],
          ['label'=>'Scenario Compare','code'=>'ANSC','route'=>'scenario-results/compare','icon'=>'columns-gap','roles'=>[],'perms'=>['ANALYTICS_VIEW']],
        ],
      ],
    ],
  ],

  [
    'label' => 'Readiness & Diagnostics',
    'code'  => 'RD',
    'icon'  => 'clipboard-check',
    'roles' => [],
    'perms' => ['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','STRATEGY_CONFIG_EDIT','STRATEGY_REPORT_VIEW','FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','CALC_ADMIN','AUDIT_VIEW','HEALTH_VIEW','METRICS_VIEW','LOGS_VIEW','SYSADMIN','ADMIN_ALL'],
    'active' => ['base-config/*','financial-config/*','strategy-config/configuration-readiness','strategy-config/resolution-check','strategy-reports/submission-readiness','strategy-reports/program-structure','transaction-calc-diagnostics/*','full-recalculation/*','diagnostics/*','health/*','application-log/*','emailqueue/*'],
    'children' => [
      [
        'label' => 'Readiness Checks',
        'code'  => 'RDRC',
        'icon'  => 'clipboard-check',
        'roles' => [],
        'perms' => ['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','STRATEGY_CONFIG_EDIT','STRATEGY_REPORT_VIEW','FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Base Configuration Readiness','code'=>'BACR','route'=>'base-config/readiness','icon'=>'clipboard-check','active'=>['base-config/*'],'roles'=>[],'perms'=>['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Strategy Configuration Readiness','code'=>'SFCR','route'=>'strategy-config/configuration-readiness','icon'=>'gear-wide-connected','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Submission Readiness','code'=>'SFSD','route'=>'strategy-reports/submission-readiness','icon'=>'clipboard-check','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Financial & Calculation Readiness','code'=>'FCCR','route'=>'financial-config/readiness','icon'=>'clipboard-data','active'=>['financial-config/*'],'roles'=>[],'perms'=>['FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Diagnostics',
        'code'  => 'RDDD',
        'icon'  => 'activity',
        'roles' => [],
        'perms' => ['STRATEGY_REPORT_VIEW','STRATEGY_CONFIG_EDIT','CALC_ADMIN','AUDIT_VIEW','HEALTH_VIEW','LOGS_VIEW','SYSADMIN','ADMIN_ALL'],
        'children' => [
          ['label'=>'Program Structure Diagnostics','code'=>'RPSD','route'=>'strategy-reports/program-structure','icon'=>'diagram-3','roles'=>[],'perms'=>['STRATEGY_REPORT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Source Resolution Check','code'=>'SFRC','route'=>'strategy-config/resolution-check','icon'=>'search','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Transaction Calc Debug','code'=>'FCTD','route'=>'transaction-calc-diagnostics/index','icon'=>'search','active'=>['transaction-calc-diagnostics/*'],'roles'=>[],'perms'=>['CALC_ADMIN','SYSADMIN','ADMIN_ALL']],
          ['label'=>'Full Recalculation','code'=>'FCFR','route'=>'full-recalculation/index','icon'=>'cpu','active'=>['full-recalculation/*'],'roles'=>[],'perms'=>['CALC_ADMIN','SYSADMIN','ADMIN_ALL']],
          ['label'=>'Application Log','code'=>'ADLG','route'=>'application-log/index','icon'=>'file-earmark-text','active'=>['application-log/*'],'roles'=>[],'perms'=>['LOGS_VIEW','METRICS_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Email Queue','code'=>'ADEQ','route'=>'emailqueue/index','icon'=>'envelope-paper','active'=>['emailqueue/*'],'roles'=>[],'perms'=>['LOGS_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_diagnostics'),'code'=>'ADDI','route'=>'diagnostics/index','icon'=>'activity','active'=>['diagnostics/*'],'roles'=>[],'perms'=>['SYSADMIN','ADMIN_ALL']],
          ['label'=>__t('menu_health'),'code'=>'ADHE','route'=>'health/index','icon'=>'heart-pulse','active'=>['health/*'],'roles'=>[],'perms'=>['HEALTH_VIEW','ADMIN_ALL','SYSADMIN']],
        ],
      ],
    ],
  ],

  [
    'label' => 'Testing Scripts',
    'code'  => 'TS',
    'icon'  => 'clipboard-check',
    'roles' => [],
    'perms' => ['TEST_SCRIPT_RUN','TEST_SCRIPT_RESULTS','TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'],
    'active' => ['screen-tests/*','screen-tests-admin/*'],
    'enabled' => $testingEnabled,
    'children' => [
      ['label' => 'My Test Scripts', 'code' => 'TSMY', 'route' => 'screen-tests/my-scripts', 'icon' => 'person-check', 'active' => ['screen-tests/my-scripts', 'screen-tests/runner'], 'roles' => [], 'perms' => ['TEST_SCRIPT_RUN','TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'], 'enabled' => $testingEnabled],
      ['label' => 'All Test Scripts', 'code' => 'TSSC', 'route' => 'screen-tests/scenarios', 'icon' => 'list-check', 'active' => ['screen-tests/scenarios'], 'roles' => [], 'perms' => ['TEST_SCRIPT_RUN','TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'], 'enabled' => $testingEnabled],
      ['label' => 'Test Results', 'code' => 'TSSR', 'route' => 'screen-tests/summary', 'icon' => 'table', 'active' => ['screen-tests/summary'], 'roles' => [], 'perms' => ['TEST_SCRIPT_RUN','TEST_SCRIPT_RESULTS','TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'], 'enabled' => $testingEnabled],
      ['label' => 'Testing Summary', 'code' => 'TSSU', 'route' => 'screen-tests-admin/summary', 'icon' => 'bar-chart-line', 'active' => ['screen-tests-admin/summary'], 'roles' => [], 'perms' => ['TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'], 'enabled' => $testingEnabled],
      ['label' => 'Assign Test Scripts', 'code' => 'TSSA', 'route' => 'screen-tests-admin/assignments', 'icon' => 'person-check', 'active' => ['screen-tests-admin/assignments'], 'roles' => [], 'perms' => ['TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'], 'enabled' => $testingEnabled],
      ['label' => 'Test Script Catalogue', 'code' => 'TSTC', 'route' => 'screen-tests-admin/scenarios', 'icon' => 'journal-text', 'active' => ['screen-tests-admin/scenarios','screen-tests-admin/scenario-form','screen-tests-admin/save-script','screen-tests-admin/reset-script','screen-tests-admin/delete-script'], 'roles' => [], 'perms' => ['TEST_SCRIPT_ADMIN','ADMIN_ALL','SYSADMIN'], 'enabled' => $testingEnabled],
    ],
  ],

  [
    'label' => 'System Configuration',
    'code'  => 'CF',
    'icon'  => 'sliders',
    'roles' => [],
    'perms' => ['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','CALC_ADMIN','STRATEGY_CONFIG_EDIT','STRATEGY_SEGMENT_PUBLISH','SYSSETTINGS_VIEW','SYSSETTINGS_EDIT','WORKFLOW_VIEW','WORKFLOW_EDIT','WORKFLOW_ADMIN','ADMIN_ALL','SYSADMIN'],
    'active' => ['fiscal-years/*','versions/*','version-types/*','currencies/*','currency-rates/*','system-settings/*','workflow-engine/*','workflow-task-types/*','workflow-task-statuses/*','workflow-assignments/*','transaction-type-segment-config/*','scenario-admin/*','report-admin/*'],
    'children' => [
      [
        'label' => 'Fiscal Context',
        'code'  => 'CFFC',
        'icon'  => 'calendar3',
        'roles' => [],
        'perms' => ['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Fiscal Years','code'=>'BAFY','route'=>'fiscal-years/list','icon'=>'calendar3','active'=>['fiscal-years/*'],'roles'=>[],'perms'=>['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Versions','code'=>'BAVR','route'=>'versions/list','icon'=>'layers','active'=>['versions/*'],'roles'=>[],'perms'=>['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Currencies','code'=>'BACU','route'=>'currencies/list','icon'=>'currency-dollar','active'=>['currencies/*'],'roles'=>[],'perms'=>['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Currency Rates','code'=>'BACX','route'=>'currency-rates/list','icon'=>'currency-exchange','active'=>['currency-rates/*'],'roles'=>[],'perms'=>['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'System Settings',
        'code'  => 'BASS',
        'icon'  => 'toggles',
        'active'=> ['system-settings/*'],
        'roles' => [],
        'perms' => ['SYSSETTINGS_VIEW','SYSSETTINGS_EDIT','SYSSETTINGS_ADMIN','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Settings Register','code'=>'BASR','route'=>'system-settings/list','icon'=>'toggles','active'=>['system-settings/list'],'roles'=>[],'perms'=>['SYSSETTINGS_VIEW','SYSSETTINGS_EDIT','SYSSETTINGS_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Usage Map','code'=>'BASU','route'=>'system-settings/usage-map','icon'=>'diagram-3','active'=>['system-settings/usage-map'],'roles'=>[],'perms'=>['SYSSETTINGS_VIEW','SYSSETTINGS_ADMIN','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Workflow Configuration',
        'code'  => 'CFWF',
        'icon'  => 'diagram-3',
        'roles' => [],
        'perms' => ['WORKFLOW_VIEW','WORKFLOW_EDIT','WORKFLOW_ADMIN','BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Workflow Engine','code'=>'BAWE','route'=>'workflow-engine/list','icon'=>'diagram-3','active'=>['workflow-engine/*'],'roles'=>[],'perms'=>['WORKFLOW_VIEW','WORKFLOW_EDIT','WORKFLOW_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Workflow Task Types','code'=>'BAWT','route'=>'workflow-task-types/list','icon'=>'list-task','active'=>['workflow-task-types/*'],'roles'=>[],'perms'=>['WORKFLOW_VIEW','WORKFLOW_EDIT','WORKFLOW_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Workflow Task Statuses','code'=>'BAWS','route'=>'workflow-task-statuses/list','icon'=>'signpost-split','active'=>['workflow-task-statuses/*'],'roles'=>[],'perms'=>['WORKFLOW_VIEW','WORKFLOW_EDIT','WORKFLOW_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Workflow Assignments','code'=>'BAWA','route'=>'workflow-assignments/list','icon'=>'person-gear','active'=>['workflow-assignments/*'],'roles'=>[],'perms'=>['BASE_CONFIG_VIEW','BASE_CONFIG_EDIT','WORKFLOW_VIEW','WORKFLOW_EDIT','WORKFLOW_ADMIN','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Financial & Calculation Configuration',
        'code'  => 'FCCF',
        'icon'  => 'calculator',
        'roles' => [],
        'perms' => ['FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','CALC_ADMIN','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Transaction Type Segment Config','code'=>'FCTS','route'=>'transaction-type-segment-config/list','icon'=>'sliders2-vertical','active'=>['transaction-type-segment-config/*'],'roles'=>[],'perms'=>['FIN_CONFIG_VIEW','FIN_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Scenario Config','code'=>'FCSC','route'=>'scenario-admin/index','icon'=>'diagram-3','active'=>['scenario-admin/*'],'roles'=>[],'perms'=>['CALC_ADMIN','SYSADMIN','ADMIN_ALL']],
        ],
      ],
      [
        'label' => 'Budget Strategy Settings',
        'code'  => 'SCFG',
        'icon'  => 'flag',
        'roles' => [],
        'perms' => ['STRATEGY_CONFIG_EDIT','STRATEGY_SEGMENT_PUBLISH','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Segment Mapping','code'=>'SFSM','route'=>'strategy-config/segment-mapping','icon'=>'sliders','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Import Dimensions','code'=>'SFID','route'=>'strategy-config/import-dashboard','icon'=>'download','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Fiscal Period Labels','code'=>'SFPL','route'=>'strategy-config/fiscal-periods','icon'=>'calendar3','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Fiscal Assumptions','code'=>'SCFA','route'=>'strategy-config/fiscal-assumptions','icon'=>'graph-up-arrow','active'=>['strategy-config/fiscal-assumptions*'],'roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Custom Phasing Profiles','code'=>'SCPP','route'=>'strategy-config/phasing-profiles','icon'=>'pie-chart','active'=>['strategy-config/phasing-profiles*'],'roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Fiscal and Version Rollover','code'=>'SFRO','route'=>'strategy-config/rollover','icon'=>'arrow-repeat','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Segment Publication','code'=>'SCPU','route'=>'strategy-publish/requests','icon'=>'upload','active'=>['strategy-publish/*'],'roles'=>[],'perms'=>['STRATEGY_SEGMENT_PUBLISH','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Custom Attributes','code'=>'SFCA','route'=>'strategy-config/custom-attributes','icon'=>'input-cursor-text','roles'=>[],'perms'=>['STRATEGY_CONFIG_EDIT','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Reporting Configuration',
        'code'  => 'CFRP',
        'icon'  => 'printer',
        'roles' => [],
        'perms' => ['ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>'Report Definitions','code'=>'CFRD','route'=>'report-admin/definitions','icon'=>'journal-text','active'=>['report-admin/definitions','report-admin/definition-form'],'roles'=>[],'perms'=>['ADMIN_ALL','SYSADMIN']],
        ],
      ],
    ],
  ],

  [
    'label' => 'Integrations',
    'code'  => 'IN',
    'icon'  => 'arrow-left-right',
    'roles' => [],
    'perms' => ['INTEGRATION_VIEW','INTEGRATION_ADMIN','INTEGRATION_RUN','ADMIN_ALL','SYSADMIN'],
    'active' => ['integration-admin/*'],
    'children' => [
      ['label'=>'Integration Dashboard','code'=>'INDD','route'=>'integration-admin/dashboard','icon'=>'speedometer2','active'=>['integration-admin/dashboard'],'roles'=>[],'perms'=>['INTEGRATION_VIEW','INTEGRATION_ADMIN','INTEGRATION_RUN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Integration Systems','code'=>'INSY','route'=>'integration-admin/systems','icon'=>'diagram-3','active'=>['integration-admin/systems','integration-admin/system-form'],'roles'=>[],'perms'=>['INTEGRATION_VIEW','INTEGRATION_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Integration Interfaces','code'=>'INIF','route'=>'integration-admin/interfaces','icon'=>'plug','active'=>['integration-admin/interfaces','integration-admin/interface-form','integration-admin/test-export'],'roles'=>[],'perms'=>['INTEGRATION_VIEW','INTEGRATION_ADMIN','INTEGRATION_RUN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Code Crosswalks','code'=>'INCW','route'=>'integration-admin/crosswalks','icon'=>'shuffle','active'=>['integration-admin/crosswalks'],'roles'=>[],'perms'=>['INTEGRATION_VIEW','INTEGRATION_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Actuals Import Review','code'=>'INAR','route'=>'integration-admin/actuals-review','icon'=>'clipboard-check','active'=>['integration-admin/actuals-review'],'roles'=>[],'perms'=>['INTEGRATION_VIEW','INTEGRATION_RUN','INTEGRATION_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Integration Run History','code'=>'INRH','route'=>'integration-admin/runs','icon'=>'clock-history','active'=>['integration-admin/runs','integration-admin/run-detail'],'roles'=>[],'perms'=>['INTEGRATION_VIEW','INTEGRATION_RUN','INTEGRATION_ADMIN','ADMIN_ALL','SYSADMIN']],
    ],
  ],

  [
    'label' => 'Workflow Operations',
    'code'  => 'WO',
    'icon'  => 'list-task',
    'roles' => [],
    'perms' => ['WORKFLOW_OPERATIONS_VIEW','WORKFLOW_OPERATIONS_EDIT','WORKFLOW_OPERATIONS_ADMIN','WORKFLOW_PROJECTS_VIEW','WORKFLOW_PROJECTS_CREATE','WORKFLOW_PROJECTS_EDIT','WORKFLOW_PROJECTS_DELETE','WORKFLOW_REQUIREMENTS_VIEW','WORKFLOW_REQUIREMENTS_CREATE','WORKFLOW_REQUIREMENTS_EDIT','WORKFLOW_REQUIREMENTS_DELETE','USERS_VIEW','USERS_ADMIN','ADMIN_ALL','SYSADMIN'],
    'active' => ['workflow/*','workflow-projects/*','workflow-requirements/*','workflow-issues/*','workflow-user-groups/*'],
    'children' => [
      ['label'=>__t('menu_workflow_tasks'),'code'=>'ADWF','route'=>'workflow/list','icon'=>'list-task','active'=>['workflow/*'],'roles'=>[],'perms'=>['WORKFLOW_OPERATIONS_VIEW','WORKFLOW_OPERATIONS_EDIT','WORKFLOW_OPERATIONS_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>__t('workflow_projects'),'code'=>'ADWP','route'=>'workflow-projects/list','icon'=>'kanban','active'=>['workflow-projects/*'],'roles'=>[],'perms'=>['WORKFLOW_PROJECTS_VIEW','WORKFLOW_PROJECTS_CREATE','WORKFLOW_PROJECTS_EDIT','WORKFLOW_PROJECTS_DELETE','WORKFLOW_OPERATIONS_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>__t('workflow_requirements'),'code'=>'ADWR','route'=>'workflow-requirements/list','icon'=>'journal-richtext','active'=>['workflow-requirements/*'],'roles'=>[],'perms'=>['WORKFLOW_REQUIREMENTS_VIEW','WORKFLOW_REQUIREMENTS_CREATE','WORKFLOW_REQUIREMENTS_EDIT','WORKFLOW_REQUIREMENTS_DELETE','WORKFLOW_OPERATIONS_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>__t('workflow_requirement_summary'),'code'=>'ADRS','route'=>'workflow-requirements/summary','icon'=>'speedometer2','active'=>['workflow-requirements/summary'],'roles'=>[],'perms'=>['WORKFLOW_REQUIREMENTS_VIEW','WORKFLOW_REQUIREMENTS_CREATE','WORKFLOW_REQUIREMENTS_EDIT','WORKFLOW_REQUIREMENTS_DELETE','WORKFLOW_OPERATIONS_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>__t('workflow_requirement_matrix'),'code'=>'ADRM','route'=>'workflow-requirements/matrix','icon'=>'diagram-3','active'=>['workflow-requirements/matrix'],'roles'=>[],'perms'=>['WORKFLOW_REQUIREMENTS_VIEW','WORKFLOW_REQUIREMENTS_CREATE','WORKFLOW_REQUIREMENTS_EDIT','WORKFLOW_REQUIREMENTS_DELETE','WORKFLOW_OPERATIONS_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>__t('workflow_issues'),'code'=>'ADWI','route'=>'workflow-issues/list','icon'=>'exclamation-triangle','active'=>['workflow-issues/*'],'roles'=>[],'perms'=>['WORKFLOW_ISSUES_VIEW','WORKFLOW_ISSUES_CREATE','WORKFLOW_ISSUES_EDIT','WORKFLOW_ISSUES_DELETE','WORKFLOW_OPERATIONS_ADMIN','ADMIN_ALL','SYSADMIN']],
      ['label'=>'Workflow User Groups','code'=>'ADWG','route'=>'workflow-user-groups/list','icon'=>'people','active'=>['workflow-user-groups/*'],'roles'=>[],'perms'=>['WORKFLOW_OPERATIONS_VIEW','WORKFLOW_OPERATIONS_EDIT','WORKFLOW_OPERATIONS_ADMIN','USERS_VIEW','USERS_ADMIN','ADMIN_ALL','SYSADMIN']],
    ],
  ],

  [
    'label' => 'Training',
    'code'  => 'TR',
    'icon'  => 'mortarboard',
    'roles' => [],
    'perms' => ['TRAINING_USER','TRAINING_ADMIN','TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],
    'active' => ['training/*','training-admin/*','training-certifications/*'],
    'enabled' => $trainingEnabled,
    'children' => [
      ['label'=>'Training Dashboard','code'=>'TRDB','route'=>'training/dashboard','icon'=>'speedometer2','active'=>['training/dashboard'],'roles'=>[],'perms'=>['TRAINING_USER','TRAINING_ADMIN','TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Training Scenarios','code'=>'TRSC','route'=>'training/scenarios','icon'=>'list-check','active'=>['training/scenarios','training/runner','training/users','training/users-edit'],'roles'=>[],'perms'=>['TRAINING_USER','TRAINING_ADMIN','TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Certifications','code'=>'TRCF','route'=>'training-certifications/modules','icon'=>'award','active'=>['training-certifications/modules','training-certifications/take','training-certifications/result'],'roles'=>[],'perms'=>['TRAINING_USER','TRAINING_ADMIN','TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Training Operations','code'=>'TROP','route'=>'training-admin/operations','icon'=>'clipboard2-check','active'=>['training-admin/operations','training-admin/session-summary','training-admin/session-dashboard','training-admin/validation'],'roles'=>[],'perms'=>['TRAINING_ADMIN','TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Training Summary','code'=>'TRSM','route'=>'training/summary','icon'=>'mortarboard','active'=>['training/summary'],'roles'=>[],'perms'=>['TRAINING_ADMIN','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Certification Results','code'=>'TRCR','route'=>'training-certifications/results','icon'=>'table','active'=>['training-certifications/results'],'roles'=>[],'perms'=>['TRAINING_ADMIN','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Training Catalogue','code'=>'TRCG','route'=>'training-admin/scenarios','icon'=>'journal-text','active'=>['training-admin/scenarios','training-admin/scenario-form','training-admin/steps','training-admin/step-form','training-admin/translations'],'roles'=>[],'perms'=>['TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Certification Catalogue','code'=>'TRCC','route'=>'training-certifications/admin','icon'=>'award-fill','active'=>['training-certifications/admin','training-certifications/form','training-certifications/questions','training-certifications/question-form'],'roles'=>[],'perms'=>['TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
      ['label'=>'Training Matrix','code'=>'TRMX','route'=>'training-admin/matrix','icon'=>'diagram-3','active'=>['training-admin/matrix'],'roles'=>[],'perms'=>['TRAINING_ADMIN','TRAINING_CONFIG','ADMIN_ALL','SYSADMIN'],'enabled'=>$trainingEnabled],
    ],
  ],

  [
    'label' => __t('menu_admin'),
    'code'  => 'AD',
    'icon'  => 'gear',
    'roles' => [],
    'perms' => ['USERS_VIEW','ROLES_VIEW','AUDIT_VIEW','HEALTH_VIEW','SESSION_VIEW','METRICS_VIEW','SYSADMIN','ADMIN_ALL'],
    'active' => ['users/*','roles/*','access-matrix/*','sessions/*','session/*','audit/*','metrics/*','health/*','application-log/*','emailqueue/*','email-templates/*'],
    'children' => [
      [
        'label' => 'Access & Security',
        'code'  => 'ADAS',
        'icon'  => 'shield-lock',
        'roles' => [],
        'perms' => ['USERS_VIEW','ROLES_VIEW','SESSION_VIEW','ADMIN_ALL','SYSADMIN'],
        'children' => [
          ['label'=>__t('menu_users'),'code'=>'ADUS','route'=>'users/list','icon'=>'people','active'=>['users/*'],'roles'=>[],'perms'=>['USERS_VIEW','USERS_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_roles'),'code'=>'ADRO','route'=>'roles/list','icon'=>'shield-lock','active'=>['roles/*'],'roles'=>[],'perms'=>['ROLES_VIEW','ROLES_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>'Access Matrix','code'=>'ADAX','route'=>'access-matrix/index','icon'=>'shield-check','active'=>['access-matrix/*'],'roles'=>[],'perms'=>['ROLES_VIEW','ROLES_ADMIN','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_active_sessions'),'code'=>'ADSE','route'=>'sessions/index','icon'=>'activity','active'=>['sessions/*'],'roles'=>[],'perms'=>['SESSION_VIEW']],
          ['label'=>__t('menu_session_vars'),'code'=>'ADSV','route'=>'session/list','icon'=>'person-badge','active'=>['session/*'],'roles'=>[],'perms'=>['SESSION_VIEW','ADMIN_ALL','SYSADMIN']],
        ],
      ],
      [
        'label' => 'Audit & Monitoring',
        'code'  => 'ADAM',
        'icon'  => 'activity',
        'roles' => [],
        'perms' => ['AUDIT_VIEW','METRICS_VIEW','HEALTH_VIEW','USERS_ADMIN','SYSADMIN','ADMIN_ALL'],
        'children' => [
          ['label'=>__t('menu_audit'),'code'=>'ADAU','route'=>'audit/list','icon'=>'journal-text','active'=>['audit/*'],'roles'=>[],'perms'=>['AUDIT_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_metrics_failed_logins'),'code'=>'ADFL','route'=>'metrics/failed-logins','icon'=>'shield-exclamation','active'=>['metrics/failed-logins'],'roles'=>[],'perms'=>['METRICS_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_metrics_errors'),'code'=>'ADER','route'=>'metrics/errors-trend','icon'=>'activity','active'=>['metrics/errors-trend'],'roles'=>[],'perms'=>['METRICS_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>__t('menu_metrics_health'),'code'=>'ADMH','route'=>'metrics/health','icon'=>'heart-pulse','active'=>['metrics/health'],'roles'=>[],'perms'=>['METRICS_VIEW','ADMIN_ALL','SYSADMIN']],
          ['label'=>'System Messages','code'=>'ADSM','route'=>'systemmessages/list','icon'=>'megaphone','active'=>['systemmessages/*'],'roles'=>[],'perms'=>['SYSADMIN','ADMIN_ALL']],
          ['label'=>'Email Templates','code'=>'ADET','route'=>'email-templates/list','icon'=>'envelope-paper','active'=>['email-templates/*'],'roles'=>[],'perms'=>['USERS_ADMIN','SYSADMIN','ADMIN_ALL']],
        ],
      ],
    ],
  ],

];
