<?php
declare(strict_types=1);

return [
    ''               => 'HomeController@index',
    'home'           => 'HomeController@index',
    'home/index'     => 'HomeController@index',

    // Auth
    'auth/loginForm'     => 'AuthController@loginForm',
    'auth/login'         => 'AuthController@login',   // POST
    'auth/tokenLogin'    => 'AuthController@tokenLogin',
    'auth/logout'        => 'AuthController@logout',  // GET
    'auth/account'       => 'AuthController@account',
    'auth/refreshAccess' => 'AuthController@refreshAccess',

    // System Settings
    'system-settings/list' => 'SystemSettingsController@list',
    'system-settings/usage-map' => 'SystemSettingsController@usageMap',
    'system-settings/save' => 'SystemSettingsController@save',
    'base-config/readiness' => 'BaseConfigurationController@readiness',

    // Users (Admin)
    'users/list'   => 'UsersController@list',
    'users/edit'   => 'UsersController@edit',
    'users/save'   => 'UsersController@save',
    'users/unlock' => 'UsersController@unlock',
    'users/saveRoles' => 'UsersController@saveRoles',
    'users/exportPdf' => 'UsersController@exportPdf',
    'users/exportUserPdf' => 'UsersController@exportUserPdf',
    'users/upload'         => 'UsersController@upload',         // GET: show form
    'users/uploadProcess'  => 'UsersController@uploadProcess',  // POST: handle file
    'users/exportExcel'   => 'UsersController@exportExcel',   // ✅ NEW Excel route

    // Roles (Admin)
    'roles/list' => 'RolesController@list',
    'roles/edit' => 'RolesController@edit',
    'roles/save' => 'RolesController@save',
    'roles/view' => 'RolesController@view',   // for role + permissions detail
    'access-matrix/index' => 'AccessMatrixController@index',

    // Audit
    'audit/list' => 'AuditController@list',

    // Diagnostics
    'diagnostics/index'          => 'DiagnosticsController@index',
    'diagnostics/sendTestEmail'  => 'DiagnosticsController@sendTestEmail',
    'diagnostics/throwException' => 'DiagnosticsController@throwException',
    'diagnostics/forceDbError'   => 'DiagnosticsController@forceDbError',
    'diagnostics/fatalError'     => 'DiagnosticsController@fatalError',

    // Language
    'lang/switch' => 'LangController@switch',
    'menu-jump/go' => 'MenuJumpController@go',

    // Health
    'health'       => 'HealthController@index',
    'health/index' => 'HealthController@index',

    // Metrics
    'metrics/failed-logins' => 'MetricsController@failedLogins',
    'metrics/errors-trend'  => 'MetricsController@errorsTrend',
    'metrics/health'        => 'MetricsController@health',
    'application-log/index' => 'ApplicationLogController@index',
    'application-log/download' => 'ApplicationLogController@download',

    // Workflow
    'workflow/list'   => 'WorkflowController@list',
    'workflow/edit'   => 'WorkflowController@edit',
    'workflow/save'   => 'WorkflowController@save',
    'workflow/transition' => 'WorkflowController@transition',
    'workflow/delete' => 'WorkflowController@delete',
    'training/runner' => 'TrainingController@runner',
    'training/users' => 'TrainingController@users',
    'training/users-edit' => 'TrainingController@usersEdit',
    'training/scenarios' => 'TrainingController@scenarios',
    'training/summary' => 'TrainingController@summary',
    'training-admin/scenarios' => 'TrainingAdminController@scenarios',
    'training-admin/scenario-form' => 'TrainingAdminController@scenarioForm',
    'training-admin/save-scenario' => 'TrainingAdminController@saveScenario',
    'training-admin/steps' => 'TrainingAdminController@steps',
    'training-admin/step-form' => 'TrainingAdminController@stepForm',
    'training-admin/save-step' => 'TrainingAdminController@saveStep',
    'training-admin/archive-step' => 'TrainingAdminController@archiveStep',
    'training-admin/translations' => 'TrainingAdminController@translations',
    'training-admin/save-translations' => 'TrainingAdminController@saveTranslations',
    'training/state' => 'TrainingController@state',
    'training/start' => 'TrainingController@start',
    'training/complete' => 'TrainingController@complete',
    'training/manage' => 'TrainingController@manage',
    'training/save-note' => 'TrainingController@saveNote',
    'training/stop' => 'TrainingController@stop',
    'training/reset' => 'TrainingController@reset',
    'screen-tests/scenarios' => 'ScreenTestsController@scenarios',
    'screen-tests/runner' => 'ScreenTestsController@runner',
    'screen-tests/start' => 'ScreenTestsController@start',
    'screen-tests/save-result' => 'ScreenTestsController@saveResult',
    'screen-tests/summary' => 'ScreenTestsController@summary',
    'screen-tests/capture-screenshot' => 'ScreenTestsController@captureScreenshot',
    'screen-tests/upload-attachment' => 'ScreenTestsController@uploadAttachment',
    'screen-tests/view-attachment' => 'ScreenTestsController@viewAttachment',
    'screen-tests/download-attachment' => 'ScreenTestsController@downloadAttachment',
    'screen-tests-admin/scenarios' => 'ScreenTestsAdminController@scenarios',
    'screen-tests-admin/scenario-form' => 'ScreenTestsAdminController@scenarioForm',
    'screen-tests-admin/save-script' => 'ScreenTestsAdminController@saveScenario',
    'screen-tests-admin/reset-script' => 'ScreenTestsAdminController@resetScenario',
    'screen-tests-admin/delete-script' => 'ScreenTestsAdminController@deleteScenario',
    'integration-admin/systems' => 'IntegrationAdminController@systems',
    'integration-admin/system-form' => 'IntegrationAdminController@systemForm',
    'integration-admin/save-system' => 'IntegrationAdminController@saveSystem',
    'integration-admin/interfaces' => 'IntegrationAdminController@interfaces',
    'integration-admin/interface-form' => 'IntegrationAdminController@interfaceForm',
    'integration-admin/save-interface' => 'IntegrationAdminController@saveInterface',
    'integration-admin/runs' => 'IntegrationAdminController@runs',
    'integration-admin/run-detail' => 'IntegrationAdminController@runDetail',
    'integration-admin/download-run-summary' => 'IntegrationAdminController@downloadRunSummary',
    'integration-admin/test-export' => 'IntegrationAdminController@testExport',
    'integration-admin/run-test-export' => 'IntegrationAdminController@runTestExport',
    'integration-admin/download-test-export' => 'IntegrationAdminController@downloadTestExport',
    'integration-admin/download-test-export-csv' => 'IntegrationAdminController@downloadTestExportCsv',
    'integration-admin/download-test-export-package' => 'IntegrationAdminController@downloadTestExportPackage',
    'reports/catalogue' => 'ReportsController@catalogue',
    'reports/context' => 'ReportsController@context',
    'reports/open' => 'ReportsController@open',
    'reports/execute' => 'ReportsController@execute',
    'reports/run' => 'ReportsController@run',
    'reports/launch' => 'ReportsController@launch',
    'reports/history' => 'ReportsController@history',
    'reports/run-detail' => 'ReportsController@runDetail',
    'report-admin/definitions' => 'ReportAdminController@definitions',
    'report-admin/definition-form' => 'ReportAdminController@definitionForm',
    'report-admin/save-definition' => 'ReportAdminController@saveDefinition',
    'workflow-assignments/list' => 'WorkflowAssignmentController@list',
    'workflow-assignments/form' => 'WorkflowAssignmentController@form',
    'workflow-assignments/save' => 'WorkflowAssignmentController@save',
    'workflow-assignments/archive' => 'WorkflowAssignmentController@archive',
    'workflow-task-types/list' => 'WorkflowTaskTypesController@list',
    'workflow-task-types/form' => 'WorkflowTaskTypesController@form',
    'workflow-task-types/save' => 'WorkflowTaskTypesController@save',
    'workflow-task-statuses/list' => 'WorkflowTaskStatusesController@list',
    'workflow-task-statuses/form' => 'WorkflowTaskStatusesController@form',
    'workflow-task-statuses/save' => 'WorkflowTaskStatusesController@save',
    'workflow-engine/list' => 'WorkflowEngineAdminController@list',
    'workflow-engine/form' => 'WorkflowEngineAdminController@form',
    'workflow-engine/save' => 'WorkflowEngineAdminController@save',
    'workflow-engine/archive' => 'WorkflowEngineAdminController@archive',
    'workflow-engine/stage-form' => 'WorkflowEngineAdminController@stageForm',
    'workflow-engine/save-stage' => 'WorkflowEngineAdminController@saveStage',
    'workflow-engine/archive-stage' => 'WorkflowEngineAdminController@archiveStage',
    'workflow-engine/action-form' => 'WorkflowEngineAdminController@actionForm',
    'workflow-engine/save-action' => 'WorkflowEngineAdminController@saveAction',
    'workflow-engine/archive-action' => 'WorkflowEngineAdminController@archiveAction',
    'workflow-engine/diagnostics' => 'WorkflowEngineAdminController@diagnostics',
    'workflow-engine/inquiry' => 'WorkflowEngineAdminController@inquiry',
    'version-types/list' => 'VersionTypesController@list',
    'version-types/form' => 'VersionTypesController@form',
    'version-types/save' => 'VersionTypesController@save',
    'dataobject-types/list' => 'DataObjectTypesController@list',
    'dataobject-types/form' => 'DataObjectTypesController@form',
    'dataobject-types/save' => 'DataObjectTypesController@save',

    // DataObject scope picker + setter
    'dataobjects/picker'   => 'DataObjectsController@picker',
    'dataobjects/select'   => 'DataObjectsController@select',
    'dataobjects/children' => 'DataObjectsController@children',

    // Fiscal context
    'context/set'          => 'ContextController@set',          // POST
    'context/listVersions' => 'ContextController@listVersions', // GET (AJAX)

    // Budget Execution
    'execution/index' => 'BudgetExecutionController@index',
    'execution/tasks' => 'BudgetExecutionController@tasks',
    'execution/use-version' => 'BudgetExecutionController@useVersion',
    'execution/save-version' => 'BudgetExecutionController@saveVersion',
    'execution/run-rollover' => 'BudgetExecutionController@runRollover',
    'execution/opening-balances' => 'BudgetExecutionController@openingBalances',
    'execution/warrants' => 'BudgetExecutionController@warrants',
    'execution/save-warrant' => 'BudgetExecutionController@saveWarrant',
    'execution/save-warrant-line' => 'BudgetExecutionController@saveWarrantLine',
    'execution/delete-warrant-line' => 'BudgetExecutionController@deleteWarrantLine',
    'execution/submit-warrant' => 'BudgetExecutionController@submitWarrant',
    'execution/forward-warrant' => 'BudgetExecutionController@forwardWarrant',
    'execution/return-warrant' => 'BudgetExecutionController@returnWarrant',
    'execution/approve-warrant' => 'BudgetExecutionController@approveWarrant',
    'execution/cancel-warrant' => 'BudgetExecutionController@cancelWarrant',
    'execution/budget-reductions' => 'BudgetExecutionController@budgetReductions',
    'execution/preview-budget-reduction' => 'BudgetExecutionController@previewBudgetReduction',
    'execution/generate-budget-reduction' => 'BudgetExecutionController@generateBudgetReduction',
    'execution/supplementaries' => 'BudgetExecutionController@supplementaries',
    'execution/save-supplementary' => 'BudgetExecutionController@saveSupplementary',
    'execution/save-supplementary-line' => 'BudgetExecutionController@saveSupplementaryLine',
    'execution/delete-supplementary-line' => 'BudgetExecutionController@deleteSupplementaryLine',
    'execution/submit-supplementary' => 'BudgetExecutionController@submitSupplementary',
    'execution/forward-supplementary' => 'BudgetExecutionController@forwardSupplementary',
    'execution/return-supplementary' => 'BudgetExecutionController@returnSupplementary',
    'execution/approve-supplementary' => 'BudgetExecutionController@approveSupplementary',
    'execution/cancel-supplementary' => 'BudgetExecutionController@cancelSupplementary',
    'execution/reservations' => 'BudgetExecutionController@reservations',
    'execution/save-reservation' => 'BudgetExecutionController@saveReservation',
    'execution/save-reservation-line' => 'BudgetExecutionController@saveReservationLine',
    'execution/delete-reservation-line' => 'BudgetExecutionController@deleteReservationLine',
    'execution/submit-reservation' => 'BudgetExecutionController@submitReservation',
    'execution/forward-reservation' => 'BudgetExecutionController@forwardReservation',
    'execution/return-reservation' => 'BudgetExecutionController@returnReservation',
    'execution/approve-reservation' => 'BudgetExecutionController@approveReservation',
    'execution/cancel-reservation' => 'BudgetExecutionController@cancelReservation',
    'execution/rie' => 'BudgetExecutionController@ries',
    'execution/save-rie' => 'BudgetExecutionController@saveRie',
    'execution/save-rie-line' => 'BudgetExecutionController@saveRieLine',
    'execution/delete-rie-line' => 'BudgetExecutionController@deleteRieLine',
    'execution/submit-rie' => 'BudgetExecutionController@submitRie',
    'execution/forward-rie' => 'BudgetExecutionController@forwardRie',
    'execution/return-rie' => 'BudgetExecutionController@returnRie',
    'execution/approve-rie' => 'BudgetExecutionController@approveRie',
    'execution/cancel-rie' => 'BudgetExecutionController@cancelRie',
    'execution/commitments' => 'BudgetExecutionController@commitments',
    'execution/save-commitment' => 'BudgetExecutionController@saveCommitment',
    'execution/save-commitment-line' => 'BudgetExecutionController@saveCommitmentLine',
    'execution/delete-commitment-line' => 'BudgetExecutionController@deleteCommitmentLine',
    'execution/submit-commitment' => 'BudgetExecutionController@submitCommitment',
    'execution/forward-commitment' => 'BudgetExecutionController@forwardCommitment',
    'execution/return-commitment' => 'BudgetExecutionController@returnCommitment',
    'execution/approve-commitment' => 'BudgetExecutionController@approveCommitment',
    'execution/cancel-commitment' => 'BudgetExecutionController@cancelCommitment',

   
    // Data Object Codes (PHP CRUD views)
    'dataobjectcodes/index'  => 'DataObjectCodesController@index',
    'dataobjectcodes/create' => 'DataObjectCodesController@create',
    'dataobjectcodes/edit'   => 'DataObjectCodesController@edit',
    'dataobjectcodes/save'   => 'DataObjectCodesController@save',   // POST
    'dataobjectcodes/delete' => 'DataObjectCodesController@delete', // POST
    'dataobjectcodes/export'   => 'DataObjectCodesController@exportXlsx',
    'dataobjectcodes/exportPdf' => 'DataObjectCodesController@exportPdf',
    'dataobjectcodes/uploadProcess' => 'DataObjectCodesController@uploadProcess',
    'dataobjectcodes/downloadTemplate' => 'DataObjectCodesController@downloadTemplate',
    'dataobjectcodes/rebuildHierarchy' => 'DataObjectCodesController@rebuildHierarchy',
    'dataobjectcodes/syncOrgFromSegments' => 'DataObjectCodesController@syncOrgFromSegments',
    'dataobjectcodes/hierarchy' => 'DataObjectCodesController@hierarchy',


    // API (JSON)
    'dataobjectcodes.api/list'   => 'DataObjectCodesApiController@list',
    'dataobjectcodes.api/get'    => 'DataObjectCodesApiController@get',
    'dataobjectcodes.api/save'   => 'DataObjectCodesApiController@save',   // POST + CSRF
    'dataobjectcodes.api/delete' => 'DataObjectCodesApiController@delete', // POST + CSRF

    // Session variables
    'session/list'  => 'SessionController@list',
    'session/index' => 'SessionController@list', // optional alias

    // User Sessions
    'sessions/index'       => 'SessionsController@index',
    'sessions/forcelogout' => 'SessionsController@forceLogout',

    // Help
    'help/show' => 'HelpController@show',

    // DataObject Workflow Status
    'dataobjectworkflow/statuses' => 'DataObjectWorkflowController@index',
    'dataobjectworkflow/buildStatuses' => 'DataObjectWorkflowController@buildStatuses',
    'dataobjectworkflow/saveStatuses' => 'DataObjectWorkflowController@saveStatuses',
    'dataobjectworkflow/getStatus' => 'DataObjectWorkflowController@getStatus',
    'dataobjectworkflow/setStatus' => 'DataObjectWorkflowController@setStatus',

    // System Messages (Admin + Feed + Email queue)
    'systemmessages/list'       => 'SystemMessageAdminController@list',       // GET
    'systemmessages/createForm' => 'SystemMessageAdminController@createForm', // GET
    'systemmessages/create'     => 'SystemMessageAdminController@create',     // POST
    'systemmessages/editForm'   => 'SystemMessageAdminController@editForm',   // GET
    'systemmessages/update'     => 'SystemMessageAdminController@update',     // POST
    'systemmessages/preview'    => 'SystemMessageAdminController@preview',    // GET
    'systemmessages/setStatus'  => 'SystemMessageAdminController@setStatus',  // POST

    'systemmessages/feed'       => 'SystemMessageFeedController@feed',        // GET (JSON)
    'systemmessages/ack'        => 'SystemMessageFeedController@ack',         // POST

    'emailqueue/process'        => 'EmailQueueController@process',            // GET (can be called by scheduler)

    // DataObjectCode Access Management
    'dataobjectcodes/access'        => 'DataObjectCodeAccessController@index',
    'dataobjectcodes/access_form'   => 'DataObjectCodeAccessController@form',
    'dataobjectcodes/access_save'   => 'DataObjectCodeAccessController@save',
    'dataobjectcodes/access_revoke' => 'DataObjectCodeAccessController@revoke',
    'dataobjectcodes/access_report' => 'DataObjectCodeAccessController@userAccessReport',

    'dashboard/index' => 'DashboardController@index',
    'dashboard'       => 'DashboardController@index',
    'dashboard/flexdash' => 'DashboardController@flexdash',  // ← THIS IS THE NEW ONE

    // Strategy / Strategic Budgeting
    'strategy/index' => 'StrategyController@index',
    'strategy'       => 'StrategyController@index',
    'strategy/framework-guide' => 'StrategyController@frameworkGuide',
    'strategy-reports/summary' => 'StrategyController@summary',
    'strategy-reports/readiness' => 'StrategyController@readiness',
    'strategy-reports/submission-readiness' => 'StrategyController@submissionReadiness',
    'strategy-reports/sector-budget' => 'StrategyController@sectorBudget',
    'strategy-reports/program-budget' => 'StrategyController@programBudget',
    'strategy-reports/project-budget' => 'StrategyController@projectBudget',
    'strategy-reports/program-structure' => 'StrategyController@programStructure',
    'strategy-reports/segment-parent-child' => 'StrategyController@segmentParentChild',
    'strategy-reports/segment-parent-child/issue-lookup' => 'StrategyController@segmentParentChildIssueLookup',
    'strategy-reports/segment-parent-child/delete-issue-row' => 'StrategyController@deleteSegmentParentChildIssueRow',
    'strategy-reports/segment-parent-child/resolve-parent-links' => 'StrategyController@resolveSegmentParentLinks',
    'strategy-reports/mtff' => 'StrategyController@mtff',
    'strategy-reports/performance' => 'StrategyController@performance',
    'strategy-fiscal/overview' => 'StrategyController@fiscalOverview',
    'strategy-fiscal/resource-envelope' => 'StrategyFiscalController@resourceEnvelope',
    'strategy-fiscal/resource-envelope-lines' => 'StrategyFiscalController@resourceEnvelopeLines',
    'strategy-fiscal/resource-envelope-form' => 'StrategyFiscalController@resourceEnvelopeForm',
    'strategy-fiscal/save-resource-envelope' => 'StrategyFiscalController@saveResourceEnvelope',
    'strategy-fiscal/delete-resource-envelope' => 'StrategyFiscalController@deleteResourceEnvelope',
    'strategy-fiscal/sector-ceilings' => 'StrategyFiscalController@sectorCeilings',
    'strategy-fiscal/save-sector-ceiling' => 'StrategyFiscalController@saveSectorCeiling',
    'strategy-fiscal/delete-sector-ceiling' => 'StrategyFiscalController@deleteSectorCeiling',
    'strategy-fiscal/copy-sector-ceilings-from-plan' => 'StrategyFiscalController@copySectorCeilingsFromPlan',
    'strategy-fiscal/allocate-remaining-sector-ceilings' => 'StrategyFiscalController@allocateRemainingSectorCeilings',
    'strategy-fiscal/ceiling-vs-plan' => 'StrategyController@ceilingVsPlan',
    'strategy-workflow/transition' => 'StrategyController@workflowTransition',
    'strategy-config/segment-mapping' => 'StrategyConfigController@segmentMapping',
    'strategy-config/configuration-readiness' => 'StrategyConfigController@configurationReadiness',
    'strategy-config/import-dashboard' => 'StrategyConfigController@importDashboard',
    'strategy-config/fiscal-periods' => 'StrategyConfigController@fiscalPeriods',
    'strategy-config/fiscal-assumptions' => 'StrategyConfigController@fiscalAssumptions',
    'strategy-config/phasing-profiles' => 'StrategyConfigController@phasingProfiles',
    'strategy-config/rollover' => 'StrategyConfigController@rollover',
    'strategy-publish/requests' => 'StrategyPublishController@requests',
    'strategy-publish/request-form' => 'StrategyPublishController@requestForm',
    'strategy-publish/save-request' => 'StrategyPublishController@saveRequest',
    'strategy-publish/request-view' => 'StrategyPublishController@requestView',
    'strategy-publish/line-form' => 'StrategyPublishController@lineForm',
    'strategy-publish/save-line' => 'StrategyPublishController@saveLine',
    'strategy-publish/delete-line' => 'StrategyPublishController@deleteLine',
    'strategy-publish/transition' => 'StrategyPublishController@transition',
    'strategy-publish/publish' => 'StrategyPublishController@publish',
    'strategy-submissions/list' => 'StrategySubmissionController@list',
    'strategy-submissions/lodgements' => 'StrategySubmissionController@lodgements',
    'strategy-submissions/reviews' => 'StrategySubmissionController@reviews',
    'strategy-submissions/approvals' => 'StrategySubmissionController@approvals',
    'strategy-submissions/report' => 'StrategySubmissionController@report',
    'strategy-submissions/form' => 'StrategySubmissionController@form',
    'strategy-submissions/save' => 'StrategySubmissionController@save',
    'strategy-submissions/view' => 'StrategySubmissionController@view',
    'strategy-submissions/line-form' => 'StrategySubmissionController@lineForm',
    'strategy-submissions/save-line' => 'StrategySubmissionController@saveLine',
    'strategy-submissions/delete-line' => 'StrategySubmissionController@deleteLine',
    'strategy-submissions/review-line' => 'StrategySubmissionController@reviewLine',
    'strategy-submissions/save-review' => 'StrategySubmissionController@saveReview',
    'strategy-submissions/save-assessment' => 'StrategySubmissionController@saveAssessment',
    'strategy-submissions/transition' => 'StrategySubmissionController@transition',
    'strategy-submissions/publish-sector-ceilings' => 'StrategySubmissionController@publishSectorCeilings',
    'strategy-submissions/upload-attachment' => 'StrategySubmissionController@uploadAttachment',
    'strategy-submissions/attachment-list' => 'StrategySubmissionController@attachmentList',
    'strategy-submissions/download-attachment' => 'StrategySubmissionController@downloadAttachment',
    'strategy-submissions/delete-attachment' => 'StrategySubmissionController@deleteAttachment',
    'strategy-config/resolution-check' => 'StrategyConfigController@resolutionCheck',
    'strategy-config/custom-attributes' => 'StrategyConfigController@customAttributes',
    'strategy-config/custom-attribute-form' => 'StrategyConfigController@customAttributeForm',
    'strategy-config/save-custom-attribute' => 'StrategyConfigController@saveCustomAttribute',
    'strategy-config/delete-custom-attribute' => 'StrategyConfigController@deleteCustomAttribute',
    'strategy-config/custom-attribute-options' => 'StrategyConfigController@customAttributeOptions',
    'strategy-config/custom-attribute-option-form' => 'StrategyConfigController@customAttributeOptionForm',
    'strategy-config/save-custom-attribute-option' => 'StrategyConfigController@saveCustomAttributeOption',
    'strategy-config/delete-custom-attribute-option' => 'StrategyConfigController@deleteCustomAttributeOption',
    'strategy-config/save-segment-mapping' => 'StrategyConfigController@saveSegmentMapping',
    'strategy-config/save-fiscal-periods' => 'StrategyConfigController@saveFiscalPeriods',
    'strategy-config/save-fiscal-assumption' => 'StrategyConfigController@saveFiscalAssumption',
    'strategy-config/delete-fiscal-assumption' => 'StrategyConfigController@deleteFiscalAssumption',
    'strategy-config/save-phasing-profile' => 'StrategyConfigController@savePhasingProfile',
    'strategy-config/delete-phasing-profile' => 'StrategyConfigController@deletePhasingProfile',
    'strategy-config/run-version-rollover' => 'StrategyConfigController@runVersionRollover',
    'strategy-config/run-fiscal-year-rollover' => 'StrategyConfigController@runFiscalYearRollover',
    'strategy-governance/narratives' => 'StrategyGovernanceController@narratives',
    'strategy-governance/narrative-form' => 'StrategyGovernanceController@narrativeForm',
    'strategy-governance/save-narrative' => 'StrategyGovernanceController@saveNarrative',
    'strategy-governance/delete-narrative' => 'StrategyGovernanceController@deleteNarrative',
    'strategy-governance/fiscal-risks' => 'StrategyGovernanceController@fiscalRisks',
    'strategy-governance/fiscal-risk-form' => 'StrategyGovernanceController@fiscalRiskForm',
    'strategy-governance/save-fiscal-risk' => 'StrategyGovernanceController@saveFiscalRisk',
    'strategy-governance/delete-fiscal-risk' => 'StrategyGovernanceController@deleteFiscalRisk',
    'strategy-governance/program-risks' => 'StrategyGovernanceController@programRisks',
    'strategy-governance/program-risk-form' => 'StrategyGovernanceController@programRiskForm',
    'strategy-governance/save-program-risk' => 'StrategyGovernanceController@saveProgramRisk',
    'strategy-governance/delete-program-risk' => 'StrategyGovernanceController@deleteProgramRisk',
    'strategy-setup/sectors' => 'StrategySetupController@sectors',
    'strategy-setup/sector-form' => 'StrategySetupController@sectorForm',
    'strategy-setup/save-sector' => 'StrategySetupController@saveSector',
    'strategy-setup/delete-sector' => 'StrategySetupController@deleteSector',
    'strategy-setup/import-sector-overlays' => 'StrategySetupController@importSectorOverlays',
    'strategy-setup/funding-types' => 'StrategySetupController@fundingTypes',
    'strategy-setup/funding-type-form' => 'StrategySetupController@fundingTypeForm',
    'strategy-setup/save-funding-type' => 'StrategySetupController@saveFundingType',
    'strategy-setup/delete-funding-type' => 'StrategySetupController@deleteFundingType',
    'strategy-setup/import-funding-type-overlays' => 'StrategySetupController@importFundingTypeOverlays',
    'strategy-setup/programs' => 'StrategySetupController@programs',
    'strategy-setup/program-form' => 'StrategySetupController@programForm',
    'strategy-setup/save-program' => 'StrategySetupController@saveProgram',
    'strategy-setup/delete-program' => 'StrategySetupController@deleteProgram',
    'strategy-setup/import-program-overlays' => 'StrategySetupController@importProgramOverlays',
    'strategy-setup/sub-programs' => 'StrategySetupController@subPrograms',
    'strategy-setup/sub-program-form' => 'StrategySetupController@subProgramForm',
    'strategy-setup/save-sub-program' => 'StrategySetupController@saveSubProgram',
    'strategy-setup/delete-sub-program' => 'StrategySetupController@deleteSubProgram',
    'strategy-setup/import-sub-program-overlays' => 'StrategySetupController@importSubProgramOverlays',
    'strategy-setup/projects' => 'StrategySetupController@projects',
    'strategy-setup/project-form' => 'StrategySetupController@projectForm',
    'strategy-setup/project-usage' => 'StrategySetupController@projectUsage',
    'strategy-setup/save-project' => 'StrategySetupController@saveProject',
    'strategy-setup/delete-project' => 'StrategySetupController@deleteProject',
    'strategy-setup/import-project-overlays' => 'StrategySetupController@importProjectOverlays',
    'strategy-setup/economic-items' => 'StrategySetupController@economicItems',
    'strategy-setup/economic-item-form' => 'StrategySetupController@economicItemForm',
    'strategy-setup/save-economic-item' => 'StrategySetupController@saveEconomicItem',
    'strategy-setup/delete-economic-item' => 'StrategySetupController@deleteEconomicItem',
    'strategy-setup/import-economic-item-overlays' => 'StrategySetupController@importEconomicItemOverlays',
    'strategy-setup/funding-sources' => 'StrategySetupController@fundingSources',
    'strategy-setup/funding-source-form' => 'StrategySetupController@fundingSourceForm',
    'strategy-setup/save-funding-source' => 'StrategySetupController@saveFundingSource',
    'strategy-setup/delete-funding-source' => 'StrategySetupController@deleteFundingSource',
    'strategy-setup/import-funding-source-overlays' => 'StrategySetupController@importFundingSourceOverlays',
    'strategy-performance/objectives' => 'StrategyPerformanceController@objectives',
    'strategy-performance/objective-form' => 'StrategyPerformanceController@objectiveForm',
    'strategy-performance/save-objective' => 'StrategyPerformanceController@saveObjective',
    'strategy-performance/delete-objective' => 'StrategyPerformanceController@deleteObjective',
    'strategy-performance/import-objective-overlays' => 'StrategyPerformanceController@importObjectiveOverlays',
    'strategy-performance/strategic-pillars' => 'StrategyPerformanceController@strategicPillars',
    'strategy-performance/strategic-pillar-form' => 'StrategyPerformanceController@strategicPillarForm',
    'strategy-performance/save-strategic-pillar' => 'StrategyPerformanceController@saveStrategicPillar',
    'strategy-performance/delete-strategic-pillar' => 'StrategyPerformanceController@deleteStrategicPillar',
    'strategy-performance/goals' => 'StrategyPerformanceController@goals',
    'strategy-performance/goal-form' => 'StrategyPerformanceController@goalForm',
    'strategy-performance/save-goal' => 'StrategyPerformanceController@saveGoal',
    'strategy-performance/delete-goal' => 'StrategyPerformanceController@deleteGoal',
    'strategy-performance/indicators' => 'StrategyPerformanceController@indicators',
    'strategy-performance/indicator-form' => 'StrategyPerformanceController@indicatorForm',
    'strategy-performance/save-indicator' => 'StrategyPerformanceController@saveIndicator',
    'strategy-performance/delete-indicator' => 'StrategyPerformanceController@deleteIndicator',
    'strategy-performance/targets' => 'StrategyPerformanceController@targets',
    'strategy-performance/target-form' => 'StrategyPerformanceController@targetForm',
    'strategy-performance/save-target' => 'StrategyPerformanceController@saveTarget',
    'strategy-performance/delete-target' => 'StrategyPerformanceController@deleteTarget',
    'strategy-delivery/outputs' => 'StrategyDeliveryController@outputs',
    'strategy-delivery/output-form' => 'StrategyDeliveryController@outputForm',
    'strategy-delivery/save-output' => 'StrategyDeliveryController@saveOutput',
    'strategy-delivery/delete-output' => 'StrategyDeliveryController@deleteOutput',
    'strategy-delivery/import-output-overlays' => 'StrategyDeliveryController@importOutputOverlays',
    'strategy-delivery/activities' => 'StrategyDeliveryController@activities',
    'strategy-delivery/activity-form' => 'StrategyDeliveryController@activityForm',
    'strategy-delivery/save-activity' => 'StrategyDeliveryController@saveActivity',
    'strategy-delivery/delete-activity' => 'StrategyDeliveryController@deleteActivity',
    'strategy-delivery/import-activity-overlays' => 'StrategyDeliveryController@importActivityOverlays',
    'strategy-delivery/budgets' => 'StrategyDeliveryController@budgets',
    'strategy-delivery/budget-form' => 'StrategyDeliveryController@budgetForm',
    'strategy-delivery/save-budget' => 'StrategyDeliveryController@saveBudget',
    'strategy-delivery/delete-budget' => 'StrategyDeliveryController@deleteBudget',

    //Analytics
    'analytics' => 'AnalyticsController@index',
    'scenario-results' => 'ScenarioResultsController@index',
    'scenario-results/index' => 'ScenarioResultsController@index',
    'scenario-results/compare' => 'ScenarioResultsController@compare',
    'scenario-results/api' => 'ScenarioResultsController@api',
    'scenario-admin' => 'ScenarioAdminController@index',
    'scenario-admin/index' => 'ScenarioAdminController@index',
    'scenario-admin/detail' => 'ScenarioAdminController@detail',
    'scenario-admin/model' => 'ScenarioAdminController@model',
    'scenario-admin/saveModel' => 'ScenarioAdminController@saveModel',
    'scenario-admin/scenario' => 'ScenarioAdminController@scenario',
    'scenario-admin/saveScenario' => 'ScenarioAdminController@saveScenario',
    'scenario-admin/node' => 'ScenarioAdminController@node',
    'scenario-admin/saveNode' => 'ScenarioAdminController@saveNode',
    'scenario-admin/values' => 'ScenarioAdminController@values',
    'scenario-admin/saveValues' => 'ScenarioAdminController@saveValues',
    'scenario-admin/rate-overrides' => 'ScenarioAdminController@rateOverrides',
    'scenario-admin/saveRateOverrides' => 'ScenarioAdminController@saveRateOverrides',
    'scenario-admin/runScenario' => 'ScenarioAdminController@runScenario',
    'scenario-admin/publishScenario' => 'ScenarioAdminController@publishScenario',
    'scenario-admin/resetScenario' => 'ScenarioAdminController@resetScenario',
    'scenario-admin/resetModelScenarios' => 'ScenarioAdminController@resetModelScenarios',
    'scenario-admin/syncLegacyFormulas' => 'ScenarioAdminController@syncLegacyFormulas',
    'scenario-admin/syncLegacyChain' => 'ScenarioAdminController@syncLegacyChain',
    'scenario-admin/run-detail' => 'ScenarioAdminController@runDetail',
    'transaction-calc-diagnostics' => 'TransactionCalculationDiagnosticsController@index',
    'transaction-calc-diagnostics/index' => 'TransactionCalculationDiagnosticsController@index',
    'transaction-calc-diagnostics/recalculate' => 'TransactionCalculationDiagnosticsController@recalculate',
    'full-recalculation' => 'FullRecalculationController@index',
    'full-recalculation/index' => 'FullRecalculationController@index',
    'full-recalculation/log' => 'FullRecalculationController@log',

    // Transaction Input
    'transaction-input/editor' => 'TransactionInputController@editor',
    'transaction-input/list'   => 'TransactionInputController@list',
    'transaction-input/download-template' => 'TransactionInputController@downloadTemplate',
    'transaction-input/upload-process' => 'TransactionInputController@uploadProcess',
    'transaction-input/stub'   => 'TransactionInputController@stub',
    'transaction-input/batch-runner' => 'TransactionInputController@batchRunner',
    'transaction-input/single-save-load-test' => 'TransactionInputController@singleSaveLoadTest',

    // Transaction Type Segment Config
    'transaction-type-segment-config/list' => 'TransactionTypeSegmentConfigController@list',
    'transaction-type-segment-config/save' => 'TransactionTypeSegmentConfigController@save',
    'transaction-type-segment-config/delete' => 'TransactionTypeSegmentConfigController@delete',
    'segment-values/list' => 'SegmentValuesController@list',
    'segment-values/form' => 'SegmentValuesController@form',
    'segment-values/upload' => 'SegmentValuesController@upload',
    'segment-values/save' => 'SegmentValuesController@save',
    'segment-values/archive' => 'SegmentValuesController@archive',
    'segment-values/uploadProcess' => 'SegmentValuesController@uploadProcess',
    'segment-values/downloadTemplate' => 'SegmentValuesController@downloadTemplate',
    'segment-values/exportExcel' => 'SegmentValuesController@exportExcel',
    'fiscal-years/list' => 'FiscalYearsController@list',
    'fiscal-years/form' => 'FiscalYearsController@form',
    'fiscal-years/save' => 'FiscalYearsController@save',
    'versions/list' => 'VersionsController@list',
    'versions/form' => 'VersionsController@form',
    'versions/save' => 'VersionsController@save',
    'currencies/list' => 'CurrenciesController@list',
    'currencies/form' => 'CurrenciesController@form',
    'currencies/save' => 'CurrenciesController@save',
    'currencies/uploadProcess' => 'CurrenciesController@uploadProcess',
    'currencies/downloadTemplate' => 'CurrenciesController@downloadTemplate',
    'currencies/exportExcel' => 'CurrenciesController@exportExcel',
    'currency-rates/list' => 'CurrencyRatesController@list',
    'currency-rates/form' => 'CurrencyRatesController@form',
    'currency-rates/save' => 'CurrencyRatesController@save',
    'currency-rates/uploadProcess' => 'CurrencyRatesController@uploadProcess',
    'currency-rates/downloadTemplate' => 'CurrencyRatesController@downloadTemplate',
    'currency-rates/exportExcel' => 'CurrencyRatesController@exportExcel',
    'segments/list' => 'SegmentsController@list',
    'segments/form' => 'SegmentsController@form',
    'segments/save' => 'SegmentsController@save',
    'segments/uploadProcess' => 'SegmentsController@uploadProcess',
    'segments/downloadTemplate' => 'SegmentsController@downloadTemplate',
    'financial-config/readiness' => 'FinancialConfigurationController@readiness',

    // Ceiling Balances
    'ceilings/balances'        => 'CeilingBalancesController@index',
    'ceilings/balances-keys'   => 'CeilingBalancesController@indexKeys',
    'ceilings/reload'          => 'CeilingBalancesController@reload',
    'ceilings/reload-balances' => 'CeilingBalancesController@reloadBalances'








];
